int edad;
int opcionPrioridad;
int temperatura;
int oxigeno;
int dolor;
int presionSistolica;
int nivelDolor;
Console.WriteLine("Se verificara los datos del paciente");
Console.WriteLine("Ingrese la edad del paciente");
edad = int.Parse(Console.ReadLine());
Console.WriteLine("Ingrese su temperatura");
temperatura = int.Parse(Console.ReadLine());
Console.WriteLine("Ingrese su saturación de oxigeno");
oxigeno = int.Parse(Console.ReadLine());
Console.WriteLine("Ingrese su presión sistólica");
presionSistolica = int.Parse(Console.ReadLine());
Console.WriteLine("Ingrese su nivel de dolor (0 a 10)");
nivelDolor = int.Parse(Console.ReadLine());
Console.WriteLine("Ingrese el nivel de prioridad");
Console.WriteLine("1. Emergencia");
Console.WriteLine("2. Consulta");
Console.WriteLine("3. Pediatria");
Console.WriteLine("4. Traumatologia");
Console.WriteLine("Elija una opción");
opcionPrioridad = int.Parse(Console.ReadLine());